services:
  postgres:
    image: postgres:16
    container_name: section7-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: section7

    ports:
      - 5432:5432